Added support for sending streams whose size cannot be computed.
atroo/node-weedfs pull request #6
Opened 2017-04-03 08:19 UTC by fabianTMC

by adding chunked transfer-encoding to the form headers.

2017-04-06 19:29 UTC, phal0r commented
Hi @fabianTMC ,

thanks for your PR. Are you aware of any disadvantages of chunked encoding for requests with known content length? I agree that this is good for streams, where the content length is not known, but since this header is applied on every write request, I would like to talk about that before merging.

2017-05-24 19:30 UTC, fabianTMC commented
Agreed. The advantage of having a Content-Length header is that the server will be able to make better decisions based on it. I'm not sure if it gets overridden by the Transfer-Encoding header though. It would be better to have a separate API option to enable chunked transfers.

2017-08-27 19:20 UTC, phal0r requested changes

2017-08-27 19:20 UTC, phal0r commented on lib/weedfs.js
> +                        headers: { 'transfer-encoding': 'chunked' }
I would suggest the same approach as in pull request #7 .

Pass headers via the opts object and set the headers when available in opts.

```
var options = Object.assign({}, url.parse(...));

if (opts.headers) {
            options.headers = opts.headers;
}
form.submit(options)
```

2018-10-08 15:48 UTC, atroo commented
Support for custom headers added with v1.4.0 (#12).

2018-10-08 15:48 UTC, closed without merging