add http header and collection name on opts
atroo/node-weedfs pull request #7
Opened 2017-06-14 06:50 UTC by gendigbadig

here i add additional argument for `read` and `find` method for passing opts.
you can add `headers` and `collection` property

2017-06-26 21:44 UTC, phal0r requested changes

2017-06-26 21:44 UTC, phal0r commented on lib/weedfs.js
> +                    if (opts) {
Since the default for opts will always be an object, this check is not necessary in my opinion

2017-06-26 21:44 UTC, phal0r commented on lib/weedfs.js
> +            if (opts) {
Since the default for opts will always be an object, this check is not necessary in my opinion

2018-10-08 15:53 UTC, atroo commented
Support for custom headers added with v1.4.0 (#12).

2018-10-08 15:53 UTC, closed without merging